- name: Download dotfiles
  git:
    repo: git://github.com/cloudfoundry/garden-windows-ci.git
    dest: ~/workspace/garden-windows-ci
    version: master
    update: yes
    accept_hostkey: yes
  become: yes
  become_user: pivotal
- name: Create symlink
  file:
    src: "~/workspace/garden-windows-ci/dotfiles/{{ item.src }}"
    dest: "~/{{ item.dest }}"
    owner: pivotal
    state: link
  with_items:
    - { src: "bash_profile", dest: ".bash_profile" }
    - { src: "git-authors", dest: ".git-authors" }
    - { src: "git-prompt.sh", dest: ".git-prompt.sh" }
    - { src: "gitconfig.shared", dest: ".gitconfig.shared" }
    - { src: "gitignore_global", dest: ".gitignore_global" }
    - { src: "tmux.conf", dest: ".tmux.conf" }
    - { src: "vimrc.local", dest: ".vimrc.local" }
    - { src: "xsessionrc", dest: ".xsessionrc" }
    - { src: "z.sh", dest: ".z.sh" }
  become: yes
  become_user: pivotal
